
plugins:
  - jekyll-paginate-v2
  
title: Personal site

description: Simple work blog
url: "https://extremumdev.github.io"
collections:
  ru_posts:
    output: true
    permalink: /ru/posts/:title/
  en_posts:
    output: true
    permalink: /en/posts/:title/
  en_projects:
    output: true
    permalink: /en/projects/:path/
  ru_projects:
    output: true
    permalink: /ru/projects/:title/
  logs:
    output: true
    permalink: /projects/logs/:title/
  ru_portfolio:
    output: true
    permalink: /ru/portfolio/:path/
  en_portfolio:
    output: true
    permalink: /en/portfolio/:path/

defaults:
  - scope:
      path: "_logs"
      type: "logs"
    values:
      layout: "log"

pagination:
  enabled: true
  per_page: 10
  title: ':title - страница :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - .gitignore
  - README.md
  - .jekyll-cache/
  - .sass-cache/
  - vendor/